/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rizaalvin
 */
public class Persiapan extends javax.swing.JFrame {

    /**
     * Creates new form Persiapan
     */
    public Persiapan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Persiapkan Amal Shalih dalam Menyambut Ramadhan");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 1350, 40);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1260, 20, 73, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1360, 70);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Bila kita menginginkan kebebasan dari neraka di bulan Ramadhan dan ingin diterima amalnya serta dihapus segala dosanya, maka harus ada bekal yang dipersiapkan.\n\n\n\nAllah ta’ala berfirman,");
        jTextArea3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea3.setEnabled(false);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 90, 1340, 93);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\KELASXI\\pbo\\New folder\\4.PNG")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 490, 510, 40);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("“Saya sama sekali belum pernah melihat rasulullah shallallahu ‘alaihi wa sallam berpuasa dalam satu bulan sebanyak puasa yang beliau lakukan di bulan Sya’ban,\ndi dalamnya beliau berpuasa sebulan penuh.” Dalam riwayat lain, “Beliau berpuasa di bulan Sya’ban, kecuali sedikit hari.\n\n\nBeliau tidak terlihat lebih banyak berpuasa di satu bulan melebihi puasanya di bulan Sya’ban, dan beliau tidak menyempurnakan puasa sebulan penuh kecuali di bulan\nRamadhan.\n\nGenerasi emas umat ini, generasi salafush shalih, meeka selalu mempersiapkan diri menyambut Ramadhan dengan sebaik-baiknya. Sebagian ulama salaf mengatakan,");
        jTextArea4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea4.setEnabled(false);
        jScrollPane4.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(10, 350, 1340, 140);

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\KELASXI\\pbo\\New folder\\2.PNG")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 180, 550, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\KELASXI\\pbo\\New folder\\3.PNG")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 310, 590, 40);

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("\"Mereka (para sahabat) berdo’a kepada Allah selama 6 bulan agar mereka dapat menjumpai bulan Ramadlan.”\n\n\n\nWahai kaum muslimin, agar buah bisa dipetik di bulan Ramadhan, harus ada benih yang disemai, dan ia harus diairi sampai menghasilkan buah yang rimbun. Puasa,\nqiyamullail, bersedekah, dan berbagai amal shalih di bulan Rajab dan Sya’ban, semua itu untuk menanam amal shalih di bulan Rajab dan diairi di bulan Sya’ban.\nTujuannya agar kita bisa memanen kelezatan puasa dan beramal shalih di bulan Ramadhan, karena lezatnya Ramadhan hanya bisa dirasakan dengan kesabaran, perjuangan,\ndan tidak datang begitu saja. Hari-hari Ramadhan tidaklah banyak, perjalanan hari-hari itu begitu cepat. Oleh sebab itu, harus ada persiapan yang sebaik-baiknya.");
        jTextArea5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea5.setEnabled(false);
        jScrollPane5.setViewportView(jTextArea5);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(10, 530, 1340, 160);

        jTextArea6.setEditable(false);
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText("Harus ada persiapan! Dengan demikian, tersingkaplah ketidakjujuran orang-orang yang tidak mempersiapkan bekal untuk berangkat menyambut Ramadhan. Oleh sebab itu,\ndalam ayat di atas mereka dihukum dengan berbagai bentuk kelemahan dan kehinaan disebabkan keengganan mereka untuk melakukan persiapan.\n\n\nSebagai persiapan menyambut Ramadhan, Rasulullah memperbanyak puasa di bulan Sya’ban. ‘Aisyah radhiallahu ‘anhu berkata,");
        jTextArea6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea6.setEnabled(false);
        jScrollPane6.setViewportView(jTextArea6);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(10, 220, 1340, 90);

        setBounds(0, 0, 1372, 731);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Persiapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Persiapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Persiapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Persiapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Persiapan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    // End of variables declaration//GEN-END:variables
}
