/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rizaalvin
 */
public class Shadaqah extends javax.swing.JFrame {

    /**
     * Creates new form Shadaqah
     */
    public Shadaqah() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Perbanyak Shadaqah");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 1350, 40);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1260, 20, 73, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1360, 70);

        jTextArea7.setEditable(false);
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText("(b). Menyediakan makanan berbuka. \n  Nabi n bersabda, “Barangsiapa menyediakan makanan berbuka bagi orang yang berpuasa, niscaya ia akan mendapat pahala seperti orang yang berpuasa tanpa mengurangi\n  pahala orang yang berpuasa itu sedikitpun”. (HR. at-Tirmidzi, hasan shahih). \n  Dalam riwayat lain dikatakan, “…mendadi penghapus dosanya dan menjadi pembebas sirinya dari api Neraka…”");
        jTextArea7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea7.setEnabled(false);
        jScrollPane7.setViewportView(jTextArea7);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(10, 350, 1340, 100);

        jTextArea8.setEditable(false);
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jTextArea8.setRows(5);
        jTextArea8.setText("Rasulullah n adalah orang yang sangat dermawan; kebaikan dan kedermawanan beliau pada bulan ini melebihi angin yang berhembus. Rasulullah n bersabda, \n“Seutama-utama shadaqah adalah shadaqah di bulan Ramadhan”. (HR. at-Tirmidzi). \n\nShadaqah ini di antaranya adalah:");
        jTextArea8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea8.setEnabled(false);
        jScrollPane8.setViewportView(jTextArea8);

        getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(10, 90, 1340, 100);

        jTextArea9.setEditable(false);
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jTextArea9.setRows(5);
        jTextArea9.setText("(a). Memberi makan. \n  Para Salafus Shalih senantiasa berlomba dalam memberi makan kepada orang lapar dan yang membutuhkan. Nabi n bersabda, “Siapa saja di antara orang mukmin yang\n  memberi makan saudaranya sesama mukmin yang lapar, niscaya Allah akan memberinya buah-buahan Surga. Siapa saja di antara orang mukmin yang memberi minum saudaranya\n  sesama mukmin yang haus, niscaya Allah akan memberinya minuman dari Rahiqul Makhtum”. (HR. at-Tirmidzi dengan sanad hasan). ");
        jTextArea9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea9.setEnabled(false);
        jScrollPane9.setViewportView(jTextArea9);

        getContentPane().add(jScrollPane9);
        jScrollPane9.setBounds(10, 220, 1340, 100);

        jTextField1.setEditable(false);
        jTextField1.setText("http://www.alsofwa.com/12897/143-maklumat-kiat-kiat-menghidupkan-bulan-ramadhan.html");
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 660, 510, 30);

        jTextField2.setEditable(false);
        jTextField2.setText("https://muslim.or.id/4150-persiapkan-diri-menyambut-ramadhan.html");
        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(950, 660, 400, 30);

        setBounds(0, 0, 1369, 731);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shadaqah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shadaqah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shadaqah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shadaqah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shadaqah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
