/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rizaalvin
 */
public class Taubat extends javax.swing.JFrame {

    /**
     * Creates new form Taubat
     */
    public Taubat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Perbarui Taubat");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 1350, 40);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1260, 20, 73, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1360, 70);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Rasulullah shallallahu ‘alaihi wa sallam bersabda,");
        jTextArea3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea3.setEnabled(false);
        getContentPane().add(jTextArea3);
        jTextArea3.setBounds(10, 90, 1340, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\KELASXI\\pbo\\New folder\\5.PNG")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(550, 120, 260, 40);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("Wahai kaum muslimin, mari kita persiapkan diri kita dengan memperbanyak amal shalih di dua bulan ini, Rajab dan Sya’ban, sebagai modal awal untuk mengarungi bulan\nRamadhan yang akan datang sebentar lagi.\n\n\nYa Allah mudahkanlah dan bimbinglah kami. Amin.");
        jTextArea4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea4.setEnabled(false);
        jScrollPane3.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 460, 1340, 100);

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("“Setiap keturunan Adam itu banyak melakukan dosa dan sebaik-baik orang yang berdosa adalah yang bertaubat.”\n\nTaubat menunjukkan tanda totalitas seorang dalam menghadapi Ramadhan. Dia ingin memasuki Ramadhan tanpa adanya sekat-sekat penghalang yang akan memperkeruh\nperjalanan selama mengarungi Ramadhan.\n\nAllah memerintahkan para hamba-Nya untuk bertaubat, karena taubat wajib dilakukan setiap saat. Allah ta’ala berfirman,");
        jTextArea5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea5.setEnabled(false);
        jScrollPane4.setViewportView(jTextArea5);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(10, 160, 1340, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\KELASXI\\pbo\\New folder\\6.PNG")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(510, 250, 330, 62);

        jTextArea6.setEditable(false);
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText("“Bertaubatlah kamu sekalian kepada Allah, Hai orang-orang yang beriman supaya kamu beruntung.” (An Nuur: 31).\n\nTaubat yang dibutuhkan bukanlah seperti taubat yang sering kita kerjakan. Kita bertaubat, lidah kita mengucapkan, “Saya memohon ampun kepada Allah”, akan tetapi\nhati kita lalai, akan tetapi setelah ucapan tersebut, dosa itu kembali terulang. Namun, yang dibutuhkan adalah totalitas dan kejujuran taubat.\n\nJangan pula taubat tersebut hanya dilakukan di bulan Ramadhan sementara di luar Ramadhan kemaksiatan kembali digalakkan. Ingat! Ramadhan merupakan momentum ketaatan\nsekaligus madrasah untuk membiasakan diri beramal shalih sehingga jiwa terdidik untuk melaksanakan ketaatan-ketaatan di sebelas bulan lainnya.");
        jTextArea6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea6.setEnabled(false);
        jScrollPane5.setViewportView(jTextArea6);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(10, 310, 1340, 120);

        jTextField1.setEditable(false);
        jTextField1.setText("http://www.alsofwa.com/12897/143-maklumat-kiat-kiat-menghidupkan-bulan-ramadhan.html");
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 660, 510, 30);

        jTextField2.setEditable(false);
        jTextField2.setText("https://muslim.or.id/4150-persiapkan-diri-menyambut-ramadhan.html");
        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(950, 660, 400, 30);

        setBounds(0, 0, 1376, 731);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Taubat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Taubat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Taubat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Taubat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Taubat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
